extends Node


signal update_motion_state
signal update_aim_state
signal update_current_ammo
signal update_max_ammo
signal primary_action
signal secondary_action
signal reload
signal update_camera_ray_collision_point
